name: Build C++ EXE

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Install CUDA Toolkit
      uses: Jimver/cuda-toolkit@v0.2.19
      with:
        cuda: '12.1.0'
        method: 'network'

    - name: Build Release x64
      run: |
        msbuild AuditionCopilot.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AuditionCopilot-Executable
        path: x64/Release/
