name: Build C++ EXE

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Install CUDA Toolkit
      uses: Jimver/cuda-toolkit@v0.2.19
      with:
        cuda: '12.1.0'
        method: 'network'
        use-cache: 'true'

    # 直接使用預設 Platform，不再指定名稱
    - name: Build Release
      run: |
        msbuild AuditionCopilot.sln /p:Configuration=Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AuditionCopilot-Executable
        path: |
          **/Release/
          **/bin/
